# Uncomment the next line to define a global platform for your project

platform :ios, '11.0'

target 'Saily Package Manager' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Saily Package Manager

    pod 'SwifterSwift'
    pod 'LTMorphingLabel'
    pod 'Alamofire', '~> 5.0.0-beta.5'
    pod 'SwiftyJSON'
    pod 'SnapKit'

end
